repos:
    - repo: https://github.com/astral-sh/uv-pre-commit
      rev: 0.11.7
      hooks:
          - id: uv-lock
          - id: uv-export
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.15.10
      hooks:
          - id: ruff
            args: [--fix]
          - id: ruff-format
    - repo: local
      hooks:
          - id: test-fast
            name: Run fast tests
            entry: just test-fast
            language: system
            pass_filenames: false
            always_run: true
